### ISSUE TITLE
[question] How can I access the search input value?

### ISSUE THREAD

**Issue by fredguth** [huntabyte/cmdk-sv#27]
I am trying to access the search input value. 
Binding to value in Command.Input binds to the selected Item.

**Comment by huntabyte** [comment]
I am not able to reproduce what you're describing.

When I `bind:value` to the `<Command.Input />` I am getting the expected behavior. Can you provide a reproduction?

**Comment by Not-Jayden** [comment]
Are you definitely binding to`<Command.Input />` and not `<Command.Root />` ? I made that mistake at first as well.

But yeah, binding to `<Command.Input />` works as expected for me.

**Comment by fredguth** [comment]
I am probably doing something wrong. Here is a MWE:
https://github.com/fredguth/cmd_mwe/blob/main/src/routes/plus/%2Bpage.svelte

**Comment by Not-Jayden** [comment]
@fredguth I believe you need to directly bind to the `Command.Input` `value` prop inside [this component](https://github.com/fredguth/cmd_mwe/blob/main/src/lib/components/ui/command/command-input.svelte) and then export it as an explicit prop. Then you should be able to bind to it in the parent component.

**Comment by fredguth** [comment]
Thank you all ! I guess @huntabyte already published a fix in shadcn-svelte.

**Comment by huntabyte** [comment]
Thanks for raising the issue @fredguth! Glad its all worked out!
