### ISSUE TITLE
Combobox search feature is bugged!

### ISSUE THREAD

**Issue by yb-cs** [huntabyte/cmdk-sv#42]
### Current Behavior

The current search feature searches based on value not on label. This is not the intended behavior.

### Expected Behavior

It is supposed to search based on the label not on value.

### Steps To Reproduce

Just test by changing the value of the items and see that the search is based on that.

**Comment by yb-cs** [comment]
hmmmm in the shadcn in nextjs the functionality is like I mentioned that is why I thought it was a bug it searches by label not by value. Since this is a direct port I thought it is a bug.. Thanks for the reply tho.

**Comment by lukeed** [comment]
Can confirm is the same behavior as shadcn-ui

**Comment by huntabyte** [comment]
> Can confirm is the same behavior as shadcn-ui

@lukeed do you mean there is a bug with this project or that it is not and has the same functionality as shadcn-ui? Just want to make sure it's working as expected.

**Comment by lukeed** [comment]
Sorry. It’s the same behavior as shadcn-ui. So this can probably be closed given that this is meant to be a 1:1 replacement. 

That said, when working with shadcn-ui directly, I did initially expect label text to be matched…but for compat sake the behavior would have to remain as it is currently

**Comment by huntabyte** [comment]
Good to hear!

@yb-cs if you're wanting to do something with some sort of `value` (like an id or something) on select, but search based on the label, you can just place the label in the text content (or value):

```svelte
{#each things as thing}
<Command.Item onSelect={() => doSomething(thing.value)}>
	{thing.label}
</Command.Item>
{/each}
```
