### ISSUE TITLE
Bug: Uncaught (in promise) TypeError: i is undefined on cmdk-sv website

### ISSUE THREAD

**Issue by Travispersson** [huntabyte/cmdk-sv#43]
Hello! 
Just wanted to report an issue i found on https://www.cmdk-sv.com/. 
Choosing the vercel option causes an uncaught TypeError. When the error is thrown no other option can be chosen. Need to reload to make it work again.

Any other option works fine.

**Comment by huntabyte** [comment]
Thank you! Will investigate!
