### ISSUE TITLE
Large `Command.List` cannot be filtered w/o crashing

### ISSUE THREAD

**Issue by lukeed** [huntabyte/cmdk-sv#45]
I have a looped Command/popover w/ 3200 items in it. It takes a while to render, but the main issue is that as soon as I attempt to type into the `Command.Input` the tab freezes with 100% CPU

This example was ported over from React and works fine after the initial slow render.

```html
<Popover.Root bind:open>
	<Popover.Trigger {disabled} asChild let:builder>
		<Button
			builders={[builder]}
			variant="outline" role="combobox"
		>
			{display || 'Select item'}
			<ChevronsUpDown class="ml-2 h-4 w-4 shrink-0 opacity-50" />
		</Button>
	</Popover.Trigger>

	<input {name} {value} hidden type="hidden" />

	<Popover.Content class="p-0 w-[400px]">
		<Command.Root loop>
			<Command.Input placeholder="Search items..." />
			<Command.Empty>No item found.</Command.Empty>

			<Command.List class="h-[var(--cmdk-list-height)] max-h-96">
				{#each $Names as txt (txt)}
					<Command.Item value={txt} onSelect={() => onItem(txt)}>
						<Check
							class={cn(
								'mr-2 h-4 w-4',
								txt === value ? 'opacity-100' : 'opacity-0'
							)}
						/> {name}
					</Command.Item>
				{/each}
			</Command.List>
		</Command.Root>
	</Popover.Content>
</Popover.Root>
```

**Comment by lukeed** [comment]
My naiive guess is that there's too much store logic happening (or not granular enough) which is why the initial render is also taking so long.

Rendering the same 3200 items into a plain `<ul>` completes almost instantly, which is also true even if I match the same DOM structure (attributes and all).

The initial render with the `Command.Root` list takes at least 8s.

**Comment by huntabyte** [comment]
Hey @lukeed, thanks for raising this issue!

I will try to find some time to investigate further. I'm hoping it is something small I've overlooked that is causing this behavior.

**Comment by huntabyte** [comment]
Hey @csjh, thanks a ton for the detailed comment and reproduction.

I'll try to find some time to dig into this further and come to some sort of solution for this issue!
