### ISSUE TITLE
Feature request: Use different value for searching and highlighting

### ISSUE THREAD

**Issue by Scooter1337** [huntabyte/cmdk-sv#52]
1. I want to search by name so in this case {team.name}
2. Team names are not unique, so if i hover over "Team 1", the other "Team 1" is also highlighted
3. Setting the value to {team.uuid} breaks the search option.

**Comment by Scooter1337** [comment]
I've currently solved this by appending the '%'.repeat(index) where % is any character that is not allowed in the team name, which makes them all unique. Not a good solution when the lists get longer, as appending will get slower.

**Comment by huntabyte** [comment]
You need unique values to search by.
