### ISSUE TITLE
Blurry text

### ISSUE THREAD

**Issue by david-plugge** [huntabyte/cmdk-sv#54]
For some reason the text gets really blurry when im focusing a random element.

In this example everything from the select item is blurry.
![blurry-command](https://github.com/huntabyte/cmdk-sv/assets/59972093/9610d821-2d1d-4bb9-acb8-a14d8e41a326)

When i zoom in a bit its fine. Pretty weird!

**Comment by david-plugge** [comment]
I'm using shadcn-svelte

**Comment by huntabyte** [comment]
Someone else had this issue if I recall, it's some sort of styling issue. If you're able to determine what is causing it, please let me know!

**Comment by huntabyte** [comment]
This is not related to cmdk-sv and is instead related to an issue with shadcn https://github.com/huntabyte/shadcn-svelte/issues/534
