### ISSUE TITLE
CommandDialog auto open or close based on input focus.

### ISSUE THREAD

**Issue by niemyjski** [huntabyte/cmdk-sv#56]
This would be really nice to have and I was surprised it wasn't the default behavior. Like I was thinking like it's a normal input box that gets transformed into a command dialog more of an auto complete but a command..

**Comment by huntabyte** [comment]
Not going to be a feature out of the box as this could be implemented programmatically. The events for `on:focus` and `on:blur` are forwarded already, so you can programmatically do whatever you'd like with the dialog's open state.

**Comment by niemyjski** [comment]
@huntabyte the problem with this is the inputbox for on:focus and on:blur change as the command list is shown, so it is not reliable.

**Comment by andoppomny** [comment]
When you select an item with the mouse, focus on the input element is lost before the onSelect handler is run. So if you hide the command items on blur, the onSelect doesn't get called. Only solution I have found is a timeout on blur to dismiss, which isn't great.
