### ISSUE TITLE
Exports issue, common js, path resolution

### ISSUE THREAD

**Issue by ynnoj1** [huntabyte/cmdk-sv#63]
I am having trouble when using the command component in shadcn-svelte and believe it may be caused by cmdk-sv.  

`ReferenceError: exports is not defined
    at /node_modules/cmdk-sv/dist/index.js:25:23`

I've tried a number of fixes aimed at handling commonjs:
- vite config optimizeDeps.include for cmdk-sv
- vite-plugin-commonjs

When commonjs fixes are applied i run into issues with resolving files in the $lib path:

✘ [ERROR] Could not resolve "$lib/internal/command-score.js"
✘ [ERROR] Could not resolve "$lib/internal/index.js"

A recent change updated the package to sveltekit 2.0, I cannot determine if it is related to this. 

To replicate this issue:
- create sveltekit project with defaults
- shadcn-svelte with defaults
- npx to add command component
- use command component
- issue resolves when cmdk-sv is commented out.

**Comment by kloon15** [comment]
Happened to me aswell on svelte 4 when upgrading from 0.0.13, rolling back fixes the issue.
