### ISSUE TITLE
Limit the number of options to be shown at once

### ISSUE THREAD

**Issue by pratikbhadane24** [huntabyte/cmdk-sv#75]
I was not able to find the limit for options in a group or list.
If it is there already please point it.

**Comment by jcmiron** [comment]
Not sure if you are asking from a view perspective but I've been able to do this by adding css (tailwindcss in my case).

E.g. adding "max-h-64 overflow-y-auto" will set a size to the list with scrolling.

**Comment by huntabyte** [comment]
What @jcmiron said. If you want strict limits then you can implement a custom filter yourself and limit it to only the first 5 or 10 or whatever.
