### ISSUE TITLE
How to get input value from Command.Input?

### ISSUE THREAD

**Issue by CyMathew** [huntabyte/cmdk-sv#76]
As a corollary to #13, I'm trying to use `Command.Input` to keep a value in sync with the underlying input but it looks like `on:change` event is never called. And `on:input` only returns a single key input at a time. How would I get this to work?

```svelte
<script>
   let query: string = "";
</script>

<Command.Root>
        <Command.Input
		value={query}
		on:change={(e) => query = e.currentTarget.value} or
                on:input={(e) => query = e.currentTarget.value}
	/>
	<Command.List>
          ...
	</Command.List>
</Command.Root>
```

**Comment by huntabyte** [comment]
`bind:value={query}`

**Comment by CyMathew** [comment]
Thank you. I can't believe I forgot about bind and tried to do it the React way.
