### ISSUE TITLE
Deleting letters from search creates duplicate entries in Svelte 5

### ISSUE THREAD

**Issue by ctiospl** [huntabyte/cmdk-sv#89]
In svelte 5
Duplicate entries are created when deleting letters from search input.

It works fine in svelte 4.

![cmdk-sv-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/c97441a4-1863-48e5-a371-95992d607bf5)

**Comment by AdrianGonz97** [comment]
[Svelte 5](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAACm2Oy6rCMBCGX2WYdY_d11oQV4IguD05i9hMJZgbybRwKH13SRQv4GIW881_mRkHbShh8zujk5awwW0IWCH_h7ykiQwTVpj8GPtM2tRHHRiMdJeNQE4CO-EEaxt8ZJhh562VTsECQ_QWBPZWXX_SJHCddXkMMUzSjAQbEChDMFSubX0Pz4GufQStTt4znLVTTfGUtudx78LIUBfHGz7oVFL4Xcpku2OU7kJt_QG_Cbf5qy-6F3p0vEB-tMMKrVd60KSw4TjS8rfcALa1oclmAQAA) (broken)

[Svelte 4](https://svelte.dev/repl/170b5319d6d542fc9551aa5f6e344dcf?version=4.2.18) (working)

**Comment by OTheNonE** [comment]
Seems like it's being worked on [here](https://github.com/huntabyte/cmdk-sv/pull/90) (just to add the relation).

**Comment by huntabyte** [comment]
Can't debug anything related to Svelte 5 when the prod version of the library is Svelte 4. These issues will be addressed once the Svelte 5 version of this project is released! Thank you!
